version: '3.8'

services:
  fur_chins:
    restart: unless-stopped
    container_name: fur_chins
    build: .
    networks:
      - server
      - app_network

  server:
    restart: unless-stopped
    build: mail
    expose:
      - 8000
    environment:
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  server:
    external: true
