version: '3.8'

services:
  fur_chins:
    restart: unless-stopped
    container_name: fur_chins
    build: .
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: server
